Update maestroe2e.yml

diff --git a/.github/workflows/maestroe2e.yml b/.github/workflows/maestroe2e.yml
--- a/.github/workflows/maestroe2e.yml
+++ b/.github/workflows/maestroe2e.yml
@@ -53,6 +53,12 @@ jobs:
           /bin/bash -c "curl -Ls 'https://get.maestro.mobile.dev' | /bin/bash"
         env:
           PATH: $HOME/.maestro/bin:$PATH
+
+        #Step 5.5: Ensure maestro is installed and in PATH
+      - name: Verify Maestro installation
+        run: |
+          # Ensure maestro is installed and accessible
+          command -v maestro || { echo "maestro not found"; exit 1; }
       # Step 6: Start Android Emulator
       - name: Start Android Emulator
         run: |
